# Generated by Django 4.2.8 on 2026-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0003_update_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã danh mục'),
        ),
    ]
