# Generated by Django 4.2.8 on 2026-04-14 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0005_update_category_and_service_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ví dụ: 60 phút, 90 phút, Gói cơ bản...', max_length=100, verbose_name='Tên gói')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời lượng (phút)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='spa_services.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Gói dịch vụ',
                'verbose_name_plural': 'Gói dịch vụ',
                'db_table': 'service_variants',
                'ordering': ['sort_order', 'duration_minutes'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicevariant',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='variant_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicevariant',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='variant_price_non_negative'),
        ),
    ]
