# Generated by Django 4.2.8 on 2026-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0007_remove_service_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh dịch vụ'),
        ),
    ]
