# Generated by Django 4.2.8 on 2026-04-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0008_change_image_to_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
    ]
