# Generated by Django 4.2.8 on 2026-04-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khách vãng lai')),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT khách vãng lai')),
                ('guest_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email khách vãng lai')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('PENDING', 'Chờ xử lý'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm bắt đầu phiên')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đóng phiên')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm tin nhắn cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('chat_code', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Mã phiên chat')),
                ('customer_type', models.CharField(default='guest', max_length=20, verbose_name='Loại khách')),
                ('guest_session_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Khóa phiên khách')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Trang bắt đầu chat')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='Xem trước tin nhắn cuối')),
                ('last_sender_type', models.CharField(blank=True, max_length=20, verbose_name='Loại người gửi cuối')),
                ('admin_unread_count', models.PositiveIntegerField(default=0, verbose_name='Tin chưa đọc phía admin')),
                ('customer_unread_count', models.PositiveIntegerField(default=0, verbose_name='Tin chưa đọc phía khách')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='customers.customerprofile', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Phiên chat',
                'db_table': 'chat_sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tham gia')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm rời phiên')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_staff', to='chat.chatsession', verbose_name='Phiên chat')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions_joined', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Nhân viên phiên chat',
                'verbose_name_plural': 'Nhân viên phiên chat',
                'db_table': 'session_staff',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=20, verbose_name='Loại người gửi')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Tên người gửi')),
                ('message_type', models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'Tệp tin')], default='text', max_length=20, verbose_name='Loại tin nhắn')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn')),
                ('attachment_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL tệp đính kèm')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/attachments/', verbose_name='Tệp đính kèm')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file')),
                ('attachment_size', models.PositiveBigIntegerField(default=0, verbose_name='Kích thước file')),
                ('attachment_content_type', models.CharField(blank=True, max_length=120, verbose_name='Kiểu file')),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã tin nhắn client')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('delivery_status', models.CharField(default='SENT', max_length=20, verbose_name='Trạng thái gửi')),
                ('status', models.CharField(default='sent', max_length=20, verbose_name='Trạng thái (legacy)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi (legacy)')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Phiên chat')),
            ],
            options={
                'verbose_name': 'Tin nhắn chat',
                'verbose_name_plural': 'Tin nhắn chat',
                'db_table': 'chat_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionstaff',
            constraint=models.CheckConstraint(check=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('join_at')), _connector='OR'), name='sessionstaff_left_at_valid'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['OPEN', 'PENDING', 'CLOSED'])), name='chatsession_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(check=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('started_at')), _connector='OR'), name='chatsession_closed_at_valid'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(check=models.Q(('last_message_at__isnull', True), ('last_message_at__gte', models.F('started_at')), _connector='OR'), name='chatsession_last_message_at_valid'),
        ),
    ]
