# Generated by Django 4.2.8 on 2026-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã phiên chat'),
        ),
    ]
