# Generated by Django 5.2.13 on 2026-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_shrink_code_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionstaff',
            name='sessionstaff_left_at_valid',
        ),
        migrations.RemoveField(
            model_name='sessionstaff',
            name='left_at',
        ),
        migrations.AddConstraint(
            model_name='sessionstaff',
            constraint=models.UniqueConstraint(fields=('session', 'staff'), name='sessionstaff_session_staff_unique'),
        ),
    ]
