# Generated by Django 4.2.8 on 2026-04-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nu', 'Nữ'), ('Khac', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo hồ sơ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'db_table': 'staff_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['Nam', 'Nu', 'Khac']), ('gender__isnull', True), _connector='OR'), name='staffprofile_gender_valid'),
        ),
    ]
