# Generated by Django 4.2.8 on 2026-04-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spa_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã khiếu nại')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên KH (snapshot)')),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT KH (snapshot)')),
                ('customer_email_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email KH (snapshot)')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề khiếu nại')),
                ('content', models.TextField(verbose_name='Nội dung khiếu nại')),
                ('incident_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xảy ra sự cố')),
                ('appointment_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mã lịch hẹn liên quan')),
                ('expected_solution', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Giải pháp mong muốn')),
                ('status', models.CharField(choices=[('NEW', 'Mới tạo'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã hoàn thành')], default='NEW', max_length=20, verbose_name='Trạng thái')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Kết quả xử lý')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm giải quyết xong')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='customers.customerprofile', verbose_name='Khách hàng')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa_services.service', verbose_name='Dịch vụ liên quan')),
            ],
            options={
                'verbose_name': 'Khiếu nại',
                'verbose_name_plural': 'Khiếu nại',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên'), ('ADMIN', 'Quản trị viên'), ('SYSTEM', 'Hệ thống')], max_length=20, verbose_name='Vai trò người gửi')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Tên người gửi')),
                ('message', models.TextField(verbose_name='Nội dung phản hồi')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='complaints.complaint', verbose_name='Khiếu nại')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Phản hồi khiếu nại',
                'verbose_name_plural': 'Phản hồi khiếu nại',
                'db_table': 'complaint_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo khiếu nại'), ('UPDATE', 'Cập nhật'), ('ASSIGN', 'Phân công'), ('REPLY', 'Phản hồi'), ('RESOLVE', 'Hoàn thành')], max_length=30, verbose_name='Hành động')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Giá trị mới')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thực hiện')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint', verbose_name='Khiếu nại')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử khiếu nại',
                'verbose_name_plural': 'Lịch sử khiếu nại',
                'db_table': 'complaint_history',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='complaintreply',
            constraint=models.CheckConstraint(check=models.Q(('sender_role__in', ['CUSTOMER', 'STAFF', 'ADMIN', 'SYSTEM'])), name='complaintreply_sender_role_valid'),
        ),
        migrations.AddIndex(
            model_name='complainthistory',
            index=models.Index(fields=['complaint', '-performed_at'], name='complaint_h_complai_fcb053_idx'),
        ),
        migrations.AddConstraint(
            model_name='complainthistory',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ['CREATE', 'UPDATE', 'ASSIGN', 'REPLY', 'RESOLVE'])), name='complainthistory_action_valid'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['code'], name='complaints_code_eadadf_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='complaints_status_f38b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to'], name='complaints_assigne_8eb502_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['NEW', 'IN_PROGRESS', 'RESOLVED'])), name='complaint_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(check=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('created_at')), _connector='OR'), name='complaint_resolved_at_valid'),
        ),
    ]
