# Generated by Django 4.2.8 on 2026-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='appointment_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã lịch hẹn liên quan'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã khiếu nại'),
        ),
    ]
