# Generated by Django 4.2.8 on 2026-04-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spa_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã lịch hẹn')),
                ('customer_name_snapshot', models.CharField(max_length=100, verbose_name='Tên khách (snapshot)')),
                ('customer_phone_snapshot', models.CharField(max_length=15, verbose_name='SĐT khách (snapshot)')),
                ('customer_email_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email khách (snapshot)')),
                ('appointment_date', models.DateField(db_index=True, verbose_name='Ngày hẹn')),
                ('appointment_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời lượng (phút)')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Số khách')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('NOT_ARRIVED', 'Chưa đến'), ('ARRIVED', 'Đã đến'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], db_index=True, default='NOT_ARRIVED', max_length=20, verbose_name='Trạng thái')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PARTIAL', 'Thanh toán một phần'), ('PAID', 'Đã thanh toán'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('source', models.CharField(choices=[('DIRECT', 'Trực tiếp'), ('ONLINE', 'Đặt online'), ('PHONE', 'Điện thoại'), ('FACEBOOK', 'Facebook'), ('ZALO', 'Zalo')], default='DIRECT', max_length=20, verbose_name='Nguồn đặt lịch')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú của khách')),
                ('staff_notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm check-in')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm check-out')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã hóa đơn')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng tiền trước chiết khấu')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số tiền chiết khấu')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thành tiền')),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PARTIAL', 'Thanh toán một phần'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ'), ('BANK_TRANSFER', 'Chuyển khoản'), ('E_WALLET', 'Ví điện tử')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='SUCCESS', max_length=20, verbose_name='Trạng thái giao dịch')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thanh toán')),
                ('recorded_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch tham chiếu')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'invoice_payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã phòng')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sức chứa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm cập nhật')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'db_table': 'rooms',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='room_capacity_positive'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.invoice', verbose_name='Hóa đơn'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.appointment', verbose_name='Lịch hẹn'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customerprofile', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.room', verbose_name='Phòng'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_services.service', verbose_name='Dịch vụ'),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.CheckConstraint(check=models.Q(('payment_method__in', ['CASH', 'CARD', 'BANK_TRANSFER', 'E_WALLET'])), name='payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.CheckConstraint(check=models.Q(('transaction_status__in', ['PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'])), name='payment_transaction_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_amount__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('final_amount__gte', 0)), name='invoice_final_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__lte', models.F('subtotal_amount'))), name='invoice_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['UNPAID', 'PARTIAL', 'PAID', 'CANCELLED', 'REFUNDED'])), name='invoice_status_valid'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_code'], name='appt_code_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'appointment_date'], name='appt_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='appt_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['room', 'appointment_date'], name='appt_room_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['source', 'status'], name='appt_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='appt_datetime_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('guests__gte', 1)), name='appointment_guests_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='appointment_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('appointment_time'))), name='appointment_end_time_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('check_out_at__isnull', True), ('check_in_at__isnull', True), ('check_out_at__gte', models.F('check_in_at')), _connector='OR'), name='appointment_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'NOT_ARRIVED', 'ARRIVED', 'COMPLETED', 'CANCELLED'])), name='appointment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['UNPAID', 'PARTIAL', 'PAID', 'REFUNDED'])), name='appointment_payment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ['DIRECT', 'ONLINE', 'PHONE', 'FACEBOOK', 'ZALO'])), name='appointment_source_valid'),
        ),
    ]
