# Generated by Django 4.2.8 on 2026-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã hóa đơn'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã phòng'),
        ),
    ]
