# Generated by Django 4.2.8 on 2026-04-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0006_add_service_variant'),
        ('appointments', '0002_shrink_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='spa_services.servicevariant', verbose_name='Gói dịch vụ'),
        ),
    ]
