# Generated by Django 4.2.8 on 2026-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_booker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT khách (snapshot)'),
        ),
    ]
