# Generated by Django 4.2.8 on 2026-04-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa_services', '0010_sync_service_variant_and_image_not_null'),
        ('appointments', '0006_booker_fields_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_duration_positive',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_end_time_after_start',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng (phút)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.room', verbose_name='Phòng'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa_services.service', verbose_name='Dịch vụ'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='appointment_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('appointment_time')), _connector='OR'), name='appointment_end_time_after_start'),
        ),
    ]
