# Generated by Django 4.2.8 on 2026-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_refactor_remove_legacy_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_status_valid',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('NOT_ARRIVED', 'Chưa đến'), ('ARRIVED', 'Đã đến'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy'), ('REJECTED', 'Đã từ chối')], db_index=True, default='NOT_ARRIVED', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'NOT_ARRIVED', 'ARRIVED', 'COMPLETED', 'CANCELLED', 'REJECTED'])), name='appointment_status_valid'),
        ),
    ]
