# Generated by Django 4.2.8 on 2026-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_booking_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'Không chiết khấu'), ('AMOUNT', 'Số tiền cố định (VNĐ)'), ('PERCENT', 'Phần trăm (%)')], default='NONE', max_length=10, verbose_name='Loại chiết khấu'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị chiết khấu (số tiền hoặc %)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('NOT_ARRIVED', 'Chưa đến'), ('ARRIVED', 'Đã đến'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], db_index=True, default='NOT_ARRIVED', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số tiền chiết khấu thực tế'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gte', 0)), name='invoice_discount_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_type__in', ['NONE', 'AMOUNT', 'PERCENT'])), name='invoice_discount_type_valid'),
        ),
    ]
