# Generated by Django 4.2.8 on 2026-05-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_add_invoice_discount_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='staff_notes',
        ),
    ]
